### PR TITLE
Promisify

### LINKED ISSUE #41: Promisify
Since Mineflayer has officially Promisified the codebase, all Mineflayer plugins should also start moving in that direction.

### PR DESCRIPTION
**Pull request by Saiv46**
Callback is now optional, if omitted - methods returns promises.

Closes #41

### CODE REVIEW

**Comment by rom1504** [comment]
Great
Did you test it manually a bit to check it works ?

**Comment by rom1504** [comment]
hey @Saiv46 ; I'd love to merge this so we can finish promisify migration of mineflayer, but I don't want to break this package
can you please confirm things work after this change?

**Comment by Saiv46** [comment]
> hey @Saiv46 ; I'd love to merge this so we can finish promisify migration of mineflayer, but I don't want to break this package can you please confirm things work after this change?

I'm literally writing a bot just to use `mineflayer-collectblock`

**Comment by rom1504** [comment]
Hey any news on this ?
Let's get this promisify business done

**Review by Saiv46 — COMMENTED** [review]
It's ready to be reviewed

**Comment by rom1504** [comment]
@Saiv46 did you test it (manually) and does it work?

**Comment by Saiv46** [comment]
> @Saiv46 did you test it (manually) and does it work?

It works on my computer with non-LTS version of Node, I need someone else to test it (and possibly suggest changes).

**Comment by rom1504** [comment]
maybe @ytcalifax ?

**Comment by ytcalifax** [comment]
> maybe @ytcalifax ?

If there is a working build provided (if needed I could also 'npm run build' it myself) I could build it  I could try testing it possibly, yeah. (I'm using Node v16.13.2)

**Comment by rom1504** [comment]
yes you can just use this pr

**Comment by ytcalifax** [comment]
After building the package, installing it locally into the bot and running my miner I seem to get this:
`PS C:\Users\ytcalifax\Downloads\0Bot> node .\index.js
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The last argument must be of type function. Received an instance of Object
    at collectCallbackified (node:util:300:5)
    at CollectBlock.<anonymous> (C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:175:61)
    at Generator.next (<anonymous>)
    at C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:4:12)
    at CollectBlock.collect (C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:168:16)
    at collectBlocks (C:\Users\ytcalifax\Downloads\0Bot\index.js:75:22)
    at EventEmitter.<anonymous> (C:\Users\ytcalifax\Downloads\0Bot\index.js:47:19)
    at EventEmitter.emit (node:events:390:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

**Comment by ytcalifax** [comment]
After building (via "npm install;npm run build"), installing the package locally into the bot and then running my mining command I get to this:
```node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The last argument must be of type function. Received an instance of Object
    at collectCallbackified (node:util:300:5)
    at CollectBlock.<anonymous> (C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:175:61)
    at Generator.next (<anonymous>)
    at C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:4:12)
    at CollectBlock.collect (C:\Users\ytcalifax\Downloads\mineflayer-collectblock-promisify\lib\CollectBlock.js:168:16)
    at collectBlocks (C:\Users\ytcalifax\Downloads\0Bot\index.js:75:22)
    at EventEmitter.<anonymous> (C:\Users\ytcalifax\Downloads\0Bot\index.js:47:19)
    at EventEmitter.emit (node:events:390:28) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by ytcalifax** [comment]
The code I used to test was the same as the one in README, just called via a command.

**Comment by rom1504** [comment]
You need to use a promise not a callback

I guess the example in the readme needs to be updated

**Comment by ytcalifax** [comment]
Oops, yeah, my bad. I'll test it using promises as soon as I can.

**Comment by Saiv46** [comment]
My bad, I tested with promises, but forgot about callbacks

**Pull request merged**
